-- 工艺码上办月度综合报表（由公网 Excel 推送解析入库）。执行一次即可。

CREATE TABLE IF NOT EXISTS mashangban_import_log (
  id BIGINT NOT NULL AUTO_INCREMENT,
  report_month CHAR(7) NOT NULL COMMENT 'YYYY-MM',
  file_name VARCHAR(255) NULL,
  file_size INT NULL,
  dept_rows INT NOT NULL DEFAULT 0,
  person_rows INT NOT NULL DEFAULT 0,
  order_rows INT NOT NULL DEFAULT 0,
  status VARCHAR(32) NOT NULL DEFAULT 'ok',
  message VARCHAR(500) NULL,
  imported_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
  PRIMARY KEY (id),
  KEY idx_msb_import_ym (report_month),
  KEY idx_msb_import_at (imported_at)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COMMENT='码上办月报导入日志';

CREATE TABLE IF NOT EXISTS mashangban_dept_monthly (
  id BIGINT NOT NULL AUTO_INCREMENT,
  report_month CHAR(7) NOT NULL COMMENT 'YYYY-MM',
  dept_name VARCHAR(64) NOT NULL COMMENT '科室名称',
  order_count INT NULL COMMENT '工单总数',
  total_service_hours DECIMAL(12,3) NULL COMMENT '总服务时长（小时）',
  avg_service_hours DECIMAL(12,3) NULL COMMENT '平均服务时长（小时）',
  avg_accept_hours DECIMAL(12,3) NULL COMMENT '平均接单时长（小时）',
  avg_arrive_hours DECIMAL(12,3) NULL COMMENT '平均到场扫码时长（小时）',
  pending_accept INT NULL COMMENT '未接单',
  pending_arrive INT NULL COMMENT '待到场',
  processing INT NULL COMMENT '处理中',
  pending_confirm INT NULL COMMENT '待确认',
  updated_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  PRIMARY KEY (id),
  UNIQUE KEY uk_msb_dept_ym (report_month, dept_name),
  KEY idx_msb_dept_ym (report_month)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COMMENT='码上办科室月度统计';

CREATE TABLE IF NOT EXISTS mashangban_person_monthly (
  id BIGINT NOT NULL AUTO_INCREMENT,
  report_month CHAR(7) NOT NULL COMMENT 'YYYY-MM',
  dept_name VARCHAR(64) NOT NULL COMMENT '来自工作表名，如水轮机室',
  employee_name VARCHAR(64) NOT NULL COMMENT '姓名',
  service_count INT NULL COMMENT '服务频次（工单）',
  total_service_hours DECIMAL(12,3) NULL COMMENT '工单总服务时长（小时）',
  type_simple INT NULL COMMENT '简易级次数',
  type_normal INT NULL COMMENT '常规级次数',
  type_complex INT NULL COMMENT '复杂级次数',
  type_hard INT NULL COMMENT '高难级次数',
  type_improve INT NULL COMMENT '工艺改进建议次数',
  avg_service_hours DECIMAL(12,3) NULL,
  avg_accept_hours DECIMAL(12,3) NULL,
  avg_arrive_hours DECIMAL(12,3) NULL,
  patrol_factory INT NULL COMMENT '厂内巡检次数',
  patrol_newtech INT NULL COMMENT '四新技术服务次数',
  patrol_follow INT NULL COMMENT '跟班服务次数',
  patrol_count INT NULL COMMENT '巡视次数',
  patrol_total_hours DECIMAL(12,3) NULL,
  patrol_avg_hours DECIMAL(12,3) NULL,
  rate_excellent INT NULL COMMENT '非常好（次）',
  rate_good INT NULL COMMENT '较好（次）',
  rate_normal INT NULL COMMENT '一般（次）',
  rate_poor INT NULL COMMENT '较差（次）',
  rate_bad INT NULL COMMENT '非常差（次）',
  updated_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  PRIMARY KEY (id),
  UNIQUE KEY uk_msb_person_ym (report_month, dept_name, employee_name),
  KEY idx_msb_person_ym (report_month),
  KEY idx_msb_person_name (employee_name)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COMMENT='码上办人员月度服务绩效';

CREATE TABLE IF NOT EXISTS mashangban_work_orders (
  id BIGINT NOT NULL AUTO_INCREMENT,
  report_month CHAR(7) NOT NULL COMMENT '所属导出月份 YYYY-MM',
  dept_name VARCHAR(64) NULL COMMENT '科室名称',
  operator_name VARCHAR(64) NULL COMMENT '操作员名称',
  order_type VARCHAR(64) NULL COMMENT '工单类型',
  order_no VARCHAR(64) NOT NULL COMMENT '工单编号',
  operator_phone VARCHAR(32) NULL,
  workshop_name VARCHAR(128) NULL COMMENT '车间名称',
  machine_name VARCHAR(255) NULL COMMENT '机床名称',
  workpiece_name VARCHAR(255) NULL COMMENT '工件名称',
  work_no VARCHAR(128) NULL COMMENT '工作号',
  assembly_no VARCHAR(128) NULL COMMENT '部套号',
  drawing_no VARCHAR(128) NULL COMMENT '图号',
  created_at_src DATETIME NULL COMMENT '工单创建时间',
  order_desc TEXT NULL COMMENT '工单说明',
  order_status VARCHAR(64) NULL COMMENT '工单状态',
  assigner_name VARCHAR(64) NULL COMMENT '分配者姓名',
  assigned_at DATETIME NULL COMMENT '分配时间',
  operator_finished_at DATETIME NULL COMMENT '操作者结束时间',
  schedule_color VARCHAR(32) NULL COMMENT '调度令颜色',
  process_finished_at DATETIME NULL COMMENT '工艺员侧结束工单时间',
  process_engineer_name VARCHAR(64) NULL COMMENT '工艺员名字',
  process_engineer_phone VARCHAR(32) NULL COMMENT '工艺员电话号',
  process_accepted_at DATETIME NULL COMMENT '工艺员接单时间',
  process_scanned_at DATETIME NULL COMMENT '工艺员扫码时间',
  process_order_status VARCHAR(64) NULL COMMENT '工艺员侧工单状态',
  rating_score VARCHAR(16) NULL COMMENT '工艺员评价分数',
  rating_label VARCHAR(64) NULL COMMENT '工艺员评价标签',
  rated_at DATETIME NULL COMMENT '评价时间',
  department VARCHAR(64) NULL COMMENT '部门',
  updated_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  PRIMARY KEY (id),
  UNIQUE KEY uk_msb_order_ym_no (report_month, order_no),
  KEY idx_msb_order_no (order_no),
  KEY idx_msb_order_ym (report_month),
  KEY idx_msb_order_dept (dept_name),
  KEY idx_msb_order_engineer (process_engineer_name),
  KEY idx_msb_order_status (order_status)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COMMENT='码上办工单明细';
